language: php

php:
  - 5.6

matrix:
  fast_finish: true

env:
  matrix:
    - ES_COMPOSER_NODEV=no
    - ES_COMPOSER_NODEV=yes

install:
  - /bin/bash ansible/provision.sh

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7" ]; then echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - if [ $ES_COMPOSER_NODEV == "no" ] && ! $(phpenv version-name | grep -q '5.3'); then sudo composer require "guzzlehttp/guzzle" "5.3.*" --dev --no-ansi --no-progress --no-interaction; fi

script:
  - make phpunit

after_script:
  - cat /var/log/elasticsearch/*.log
  - cat /var/log/nginx/*.log
  - sudo rm composer.lock && sudo composer require satooshi/php-coveralls dev-master --no-ansi --no-progress --no-interaction
  - vendor/bin/coveralls -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
